sql/scratchpad.sql
Added queries for a few more tables, including ss_perf for performance measures. Still trying to decipher ss_data and associated tables.
=> Additional queries for exploring Budget database.

budget_proj/budget_app/models.py, budget_proj/budget_app/views.py, budget_proj/budget_proj/urls.py
Fixed some invalid references, so that it is now possible to start the server without errors:
`python3 manage.py runserver`
The web app still does not run correctly, but at least the server will start.
=> Fixed invalid references in budget_proj

README.md
Fixed incorrect directory references in README.md, so that instructions for developers can run without errors.
=> Fixed directory references.

budget_proj/budget_app/management/commands/importcsv.py
This adds a new importcsv command to manage.py that imports into the Django models. It is adapted from some code that I wrote last season for the Hunger team.
=> Add importcsv command

budget_proj/budget_app/urls.py, budget_proj/budget_proj/settings.py
added swagger to our project, but I am unsure if the swagger schema view title is correct.
locate:
budget_app/urls.py
line 5
title='hackoregon_budget'
that's the title of my hackoregon repo, but unsure if that's the correct one to add to our master branch.
=> adding django-rest swagger

budget_proj/budget_app/tests.py, budget_proj/requirements.txt
This is the first automated test to be added to this project.
It verifies that the web server hosting the endpoint is up and responding.  It does not determine if a valid response is sent by the API (this can be a separate test or many).
This test will be helpful for Travis automated builds to verify that nothing has taken the API completely offline.  (Necessary but not sufficient testing.)
I copied shamelessly from the tests being developed by the Housing backend team:
https://github.com/hackoregon/housing-backend/blob/master/backend/housing_backend/tests/test_API.py
- `git pull`
- `git checkout start-testing`
- `./budget_proj/bin/test-proj.sh`
You should observe the following output:
```
$ ./budget_proj/bin/test-proj.sh 
Running test_proj.sh...
Creating test database for alias …
```
=> simple health test for each endpoint

budget_proj/budget_app/urls.py, budget_proj/budget_proj/settings.py
Noticed a complaint I knew how to fix, looked for others.
Left those alone that were "line too long" and "missing docstring" (those are never-ending issues).
It's possible to ignore these other messages globally, but figured the team should discuss that kind of change first.
=> fixing minor complaints from pylint

budget_proj/budget_app/views.py
i *think* this fixes issue #87.  Full disclosure: I've been absent the two weeks and cant test this locally yet.
Problem was a javascript-like `if` statement.
=> fix syntax error in views

sql/View-HistorySummaryByBureau.sql, sql/View-HistorySummaryByBureauFund.sql, sql/View-HistorySummaryByServiceArea.sql
- HistorySummaryByServiceArea: Subtotals Budget History by Service Area
- HistorySummaryByBureau: Subtotals Budget History by Service Area &
Bureau
- HistorySummaryByBureauFund: Subtotals Budget History by Service Area,
Bureau & Funding type
=> Adding some database views

README.md
The instructions are given with the assumption that developer is in the top-level directory.
=> Fixed path to requirements file.

budget_proj/budget_app/serializers.py, budget_proj/budget_app/urls.py, budget_proj/budget_app/views.py
added HistorySummaryByServiceAreaObjCodeSerializer in Serializers
added HistorySummaryByServiceAreaObjCode in Views
added history/sa/objcode in URLs
=> added HistorySummaryByServiceAreaObjCodeSerializer endpoint

budget_proj/bin/docker-push.sh, budget_proj/budget_proj/settings/production.py
This allows the Budget Django app to respond when request comes to the URLs:
service.civicpdx.org/budget/
service.civicpdx.com/budget/
=> deploy with the dynamically-configured ALLOWED_HOSTS

Data/sample-responses/README_SampleResponses.md, Data/sample-responses/code-all_types.json, Data/sample-responses/code-bureau_code.json, Data/sample-responses/code-service_area_code.json, Data/sample-responses/history-bureau.json, Data/sample-responses/history-service_area-object_code.json, Data/sample-responses/history-service_area.json, README.md
This may not be necessary, since the integration environment is up and running again. But just in case, I have committed sample data from responses for the queries that the UI should/might be using.
Note: I ran the JSON through a "pretty print" method that puts the attributes in alphabetical order. So the data here might look different than what you see in your browser, but the data is equivalent.
=> Sample responses for primary queries.

budget_proj/budget_proj/wsgi.py
Re-enables local development outside the Docker container.
Fixes #128.
=> Addresses RuntimeError caused by monkey.patch_all()

budget_proj/budget_app/urls.py
Found a weird cryptic string, gave it a better name
=> giving our Swagger view a sensible title

budget_proj/bin/docker-push.sh, budget_proj/budget_proj/settings/base.py, budget_proj/budget_proj/wsgi.py, budget_proj/requirements/common.txt
You know how we used to have the pretty Swagger UI wrapping its warm, loving embrace around our Django code?
Does anyone have any clue how that abandoned us so suddenly, like an orphan on the doorstep of a horror-movie orphanage?
Well, the answers to neither of these questions matter anymore.
Thanks in huge part to the leadership and dogged determination/(stupidity?) of Brian Grant from the Emergency Response team, we have a solution that allows us to deploy `Debug=False` in AWS *and* to revive the eye-pleasing Swagger UI.
=> You want pretty?  Here's pretty (back)

budget_proj/budget_proj/settings/base.py
Increased page size from 100 to 2500. Just experimenting, because 100 is much too small for doing query on the 10 years of history for data exploration.
=> Experimenting with page size.

budget_proj/budget_proj/settings/base.py
* Still experimenting with page size. Goal is to allow the largest size possible without overloading the server.
* 2500 was too big. Received 504 Gateway error.
* This time, I am trying 1000 as the page size.
=> Reduced page size.

R/pdx-budget-explorer/R/data.R, R/pdx-budget-explorer/server.R, R/pdx-budget-explorer/ui.R
"Borrowed" code from @smithjd 's [graphs-1.Rmd](https://github.com/smithjd/hack_or_budget/blob/master/graphs-1.Rmd)
=> Implemented the 'Enterprise Fund' tab.

budget_proj/budget_app/serializers.py, budget_proj/budget_app/views.py
- Refactored code for #135 
- Added calculated SA field to  HistorySummaryByBureau
=> Moss calc sa

budget_proj/bin/docker-push.sh
With any luck this will be an optional change - may not even need to merge it, so long as it kicks off an ECS deploy.
=> testing out the use of the verbose versions of the command-line parameters

budget_proj/bin/docker-push.sh
this needs to be added to support CI/CD for this repo
=> Adding the newly-required flag to enable authentication again
