hackoregon/team-budget

budget_proj/budget_app/views.py, budget_proj/budget_proj/settings.py
closes #23 
Added another constant to the django settings with proper location of the data directory.  Access it with `from django.conf import settings     settings.BASE_DATA_DIR`
Also moved the csv parsing logic into their own functions, so we can use the generics.Listview interface the same way we will when we get data in the db.
=> fix fragile csv finding in KPM/OCRB viewss

README.md, budget_proj/budget_app/models.py, budget_proj/budget_app/serializers.py, budget_proj/budget_app/urls.py, budget_proj/budget_app/views.py
I did this work, because it seems like the implementation of `OCRB` and `KPM` endpoints is working around Django, rather than using key elements of the framework. I wanted to use `filter` and `order_by` on the `all_obj` object (prior to pull request #25), but I could not see how to do that. I also wanted the Models to be attached to the database. So I implemented a `summary` endpoint that assumes data has been loaded into the database, e.g. using Aaron's `importcsv` utility. See the `README` file for how to load the database. The implementation demonstrates an API that uses query parameters for filtering the values returned by the web service. I would like to add Swagger annotations to document the options, but for now I provided a few sample queries in the view documentation, which …
=> Implemented 'summary' endpoint that filters on query parameter values.

README.md, requirements.txt
I removed redundant lines from 'requirements.txt', which were causing an error:
```
$ pip install -r requirements.txt
Double requirement given: django-rest-swagger (from -r requirements.txt (line 13)) (already in django-rest-swagger==2.1.1 (from -r requirements.txt (line 4)), name='django-rest-swagger')
```
I also added to README.md about when to run the migrate.
=> Fixed 'Double requirement given' error on pip install.

budget_proj/Dockerfile
Fixed another bad reference to the old KPM CSV file name that had an embedded space.
This fix allowed me to run the `build-proj.sh` file locally without errors.
I think the `travis.yml` file still has an error. I'm guessing that the reference to `build-proj.sh` should be: `./budget-proj/bin/build-proj.sh`, but I don't know anything about Travis.
=> Fixed bad file reference in Dockerfile.

LICENSE.txt, README.md
Added a license, so that it is clear under what conditions Hack Oregon allows others to use their software. Specifying a license is recommended by GitHub and many other people and organizations.
=> Specified a license

budget_proj/budget_proj/settings.py
I need to add this IP address to ALLOWED_HOSTS to be able to troubleshoot Docker builds.
It harms nothing for any staging, integration or production release as it's a non-routable address that will never be used in any of the Virtual Private Cloud configurations we plan to enable in AWS.
If you like, we can file an issue in this repo to remove this address from `settings.py` in the future.
=> Please add this 192 address for the forseeable future to troubleshoot Docker builds

.travis.yml, budget_proj/bin/build-proj.sh
In an alternate universe yesterday (#53 & #54), I was able to get Travis to successfully build a Docker container with our current Django API endpoints.  However, that universe collapsed after I continued to play with the laws of physics (kept committing changes before I realized I hadn't created a separate branch).  I finally abandoned that effort and started over today from `master`.
This PR is the smallest successful demonstration of Docker building the container via Travis:
https://travis-ci.org/hackoregon/team-budget/builds/209881091
It should also build successfully from your local machine.  [I swear I tested this three ways today before committing the PR.  I'm praying to the lords of the bitstream this works today.]
- `git checkout docker_and_travis`
- …
=> Docker container successfully built locally and under Travis

budget_proj/bin/test-proj.sh
For all PRs submitted to this project, there are two Travis builds that are kicked off:
- continuous-integration/travis-ci/pr
- continuous-integration/travis-ci/push
The `pr` build always fails, and the `push` build usually passes.
The tail end of the Travis build log for the `pr` build always ends with these messages:
```
Step 12 : WORKDIR /code
---> Running in 28c1d878ad69
---> 1323f3a5a0b5
Removing intermediate container 28c1d878ad69
Successfully built 1323f3a5a0b5
WARNING: Image for service budget-service was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating test database for alias 'default'...
Got an error creating the test database: database "test_budget" already exists
Type 'yes' if you would …
```
=> suppressing warnings to enable travis to successfully build a PR

budget_proj/bin/test-entrypoint.sh
Removing the whole file where a redundant call is made to `getconfig.sh` - turns out this script is no longer being used anywhere in this project.
I've tested this both locally and via Travis, and both still build and test fine without this script.
=> Removing test-entrypoint.sh [not needed]

budget_proj/Dockerfile
On the basis of PR #74, I'm now ready to cleanup tech debt in the build process and rely on the Travis build status to confirm I haven't broken anything (via the basic functional tests).
This cleanup removes three things:
1. The now-redundant download of CSV data to the Docker image.  @mxmoss confirmed for me (again, due to my poor memory) that as of a week ago, the Django APIs were all relying on the external database rather than imported CSVs to construct their data responses.
2. The unreliable `python:latest` image, that @tedbrunner was unable to download when building the Docker container locally [while testing PR #74] on his Linux computer - he received an error "UNAUTHORIZED - authentication required" at step 1 of the docker container build, which corresponds to the error I see when …
=> [tech debt] Cleaning up the Dockerfile

.travis.yml, budget_proj/Dockerfile, budget_proj/bin/docker-push.sh, budget_proj/bin/ecs-deploy.sh, budget_proj/bin/env-template.sh, budget_proj/bin/getconfig.sh, budget_proj/bin/test-entrypoint.sh, budget_proj/bin/test-proj.sh, budget_proj/budget_app/tests.py, budget_proj/budget_proj/settings.py, budget_proj/budget_proj/urls.py, budget_proj/local-docker-compose.yml, budget_proj/travis-docker-compose.yml
We now have successful deployment to AWS ECS (EC2 Container Service).
This makes our project only the second to complete deployment of a Docker container **with integrated testing** into the INTEGRATION environment in AWS.
You can find the live INTEGRATION (i.e. non-production) endpoints responding here:
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/budget/
The hosting of all containerized APIs under one roof necessitated using a single FQDN and hosting each project's API's beneath a named route e.g. `/budget`.
This means that when you test out the Docker container locally, from now on instead of browsing to http://localhost:8000/, you'll have to browse to http://localhost:8000/budget.  The `/` route is currently not configured to redirect (I couldn't find a pattern …
=> Enable Deployment to AWS ECS

.travis.yml, budget_proj/bin/docker-entrypoint.sh, budget_proj/bin/getconfig.sh, budget_proj/bin/test-entrypoint.sh
Clean up unnecessary (and confusing, for other DevOps engineers at least) PATH statements in the build.  May have to add some back if there are other tools installed as a result of enabling CD (continuous deployment).
While I'm at it, finally understood whether to use the command line parameters for installing the awscli - in a word, yes - at least [according to the AWS CLI docs](http://docs.aws.amazon.com/cli/latest/userguide/installing.html).
=> [Tech debt] Clean up the install of the AWS CLI

budget_proj/bin/build-proj.sh, budget_proj/bin/start-proj.sh, budget_proj/bin/test-proj.sh, budget_proj/budget_proj/project_config_template.py
The current scripts just give the user a blank response if they don't include the `-l` or `-t` required parameter.
This enhancement enables the user to know what to do if they've forgotten the parameter.
- `git pull`
- `git checkout usage-prompts`
- `./budget_proj/bin/test-proj.sh`
Expected response: nothing appears to happen.
Then try running `./budget_proj/bin/test-proj.sh -l` and you'll see the Docker build and tests run.
=> Usage message proactive prompt

budget_proj/bin/docker-entrypoint.sh, budget_proj/requirements.txt
If you're following the ridiculously thorough investigations, Brian Grant and I are chasing down the source of the [CRITICAL] WORKER TIMEOUT errors we're seeing in most of the containers - see [Devops-17 Issue 49](https://github.com/hackoregon/devops-17/issues/49) for details.
It appears that we're suffering from some confluence of behaviours that only shows up with ELB, Docker and gunicorn are used together to host applications in a load-balanced cluster.
There are multiple reports from [this gunicorn issue](https://github.com/benoitc/gunicorn/issues/1194) that the "sync" worker default is largely implicated, and that switching to the "gevent" worker type mitigates the issue.  [I'm still not entirely convinced that this is the right architectural decision - there ought to be a way to …
=> Replace sync workers with eventlet workers to eliminate the [CRITICAL] WORKER TIMEOUT errors

budget_proj/budget_app/tests.py
Determine whether anything has broken the API response such that non-JSON data gets returned.
I've added tests, based on [homelessness project](https://github.com/hackoregon/teamHomelessness/blob/master/homelessAPI/homelessApp/tests.py), to verify that expected JSON data is being returned from API requests.
For each endpoint, the test only verifies a single field (e.g. "fy" or "fiscal_year" where that field exists, and "code" for the /code endpoint).
You can verify the tests are working in the Travis builds by reviewing [this build](
https://travis-ci.org/hackoregon/team-budget/builds/214398088), lines 425-431.
To verify the tests run in your local environment:
- `git pull`
- `git checkout mikethecanuck/tests-for-api-data`
- `budget_proj/bin/test-proj.sh -l`
You should see the end of the …
=> New tests: verify the APIs return JSON data

.gitignore
Fixed `.gitignore` to ignore the `budget_db.sqlite3` file always, regardless of the directory in which it is created. That file is only used for local development and should not be committed to the team's repository.
`budget_db.sqlite3` is created in the directory from which the `runserver` call is made. For me, that is the top level `team-budget` directory. Other people run `runserver` from the `team-budget/budget_proj` directory.
=> Ignore budget_db.sqlite3 file.

budget_proj/bin/docker-entrypoint.sh
Gevent worker is there to workaround the assumption that ALB is still running into the same [ELB/gunicorn issue discussed here](https://github.com/benoitc/gunicorn/issues/1194).
=> Documenting the use of Gevent worker

budget_proj/budget_app/filters.py, budget_proj/budget_app/tests.py, budget_proj/budget_app/views.py, budget_proj/budget_proj/settings/base.py
Defaulting to 100 objects per response.  Can customize as needed for different views.
Here's a snippet of the new response format:
GET http://127.0.0.1:8000/budget/ocrb/
```json
{
"count": 264,
"next": "http://127.0.0.1:8000/budget/ocrb/?page=2",
"previous": null,
"results": [
{
"source_document": "FY 2015-16 Budget in Brief",
"service_area": "City Support Services",
"bureau": "City Budget Office",
"budget_category": "Capital",
"amount": 238525,
"fy": "2013-14",
"budget_type": "Actual"
},
{
"source_document": "FY 2015-16 Budget in Brief",
"service_area": "City Support Services",
"bureau": "City Budget Office",
"budget_category": "Operating",
"amount": 1578188,
"fy": "2013-14",
"budget_type": "Actual"
},
{
"source_document": "FY 2015-16 Budget in Brief",
"service_area": "City Support …
```
=> hack pagination into ocrb view

budget_proj/bin/docker-entrypoint.sh
Gunicorn as the web frontend for our Django APIs [recommends](http://docs.gunicorn.org/en/stable/settings.html#workers) > 1 workers depending on the number of CPU cores available.  Each of our API containers in Hack Oregon is allocated a single CPU core, so the recommended advice generally converges on three workers.
I've tested this before and it appears to work just fine.  Plus it sets us up to be able to handle far more concurrent connections when/if these APIs start seeing some real use.
=> using the recommended number of workers

budget_proj/bin/docker-entrypoint.sh, budget_proj/bin/docker-push.sh, budget_proj/budget_proj/wsgi.py, budget_proj/requirements/prod.txt
At today's mini-hack the DevOps squad tackled the slowness and timeouts in all the backend projects.
We were observing numerous, frequent, and repetitive CRITICAL WORKER TIMEOUT errors in the logs for the deployed containers, and noticed these correlated with slow endpoint responses and/or occasional timeouts, 502/504 errors and other issues.
This PR reflects the results of our research that finally extinguished that behaviour.
=> Stabilizing the app in AWS - driving out CRITICAL WORKER TIMEOUT issue

budget_proj/requirements/common.txt, budget_proj/requirements/prod.txt
moss pointed out these packages are necessary for local dev too - and all packages are now pinned to a version.
Fixes #124 and #125 .
=> Fixes for 124 and 125

R/pdx-budget-explorer/DESCRIPTION, R/pdx-budget-explorer/README.md, R/pdx-budget-explorer/budgetLevels.R, R/pdx-budget-explorer/commonConstants.R, R/pdx-budget-explorer/data.R, R/pdx-budget-explorer/server.R, R/pdx-budget-explorer/ui.R, budget_proj/budget_proj/settings/base.py
* The Shiny-based web application now has tabs.
* I used @smithjd 's code to create a 'Personnel' tab in the R code. The set of tables display very small, so they do not look as good as when running from his [Rmarkdown script](https://github.com/smithjd/hack_or_budget/blob/master/graphs-1.Rmd). We need to fix that, but I will still merge these changes, because it is at least a step forward. The display panel probably needs to be sized.
* The data layer can now handle the paging from the web service at least for the general /history endpoint. We need to change the size of pages though. It takes a **long** time for the 'Personnel' tab to display, because the app has to access 228 pages from the web service.
* Cleaned up some of the constants.
=> Integrated 'Personnel' plot.

budget_proj/budget_proj/settings/base.py
* Still experimenting. Page size 1000 led to 504 Gateway error in one call, although another call completed.
* This commit tries a smaller page size of 680 rows in web service response.
=> Reduced page size from 1000 to 680 to avoid 'Gateway' errors.

Data/DemoData-20170501.csv, Data/README_DataSources.md, budget_proj/requirements/common.txt
Having a small file allows us to open it quickly and browse around it in the GitHub viewer to see the format. We do not care about the actual data in this file. It is just to demonstrate the format of the larger history file.
=> Added a very small file of sample data for display at Demo Day.

R/pdx-budget-explorer/R/commonConstants.R, R/pdx-budget-explorer/server.R
Pull Request #146 changed variable name returned by web service using `HistorySummaryByServiceAreaSerializer` from `service_area_code` to `sa_calced`. This pull request integrates the R web application with that change. The `Service Areas by Fiscal Year` plot now shows all 7 Service Areas, rather than just 6.
=> Changed variable from 'service_area_code' to 'sa_calced'

R/pdx-budget-explorer/R/commonConstants.R, R/pdx-budget-explorer/R/data.R, R/pdx-budget-explorer/server.R
Transforms new 'sa_calced' column into 'service_area_code' in the data layer. Then the rest of the code can assume the canonical 'service_area_code'.
=> Fixed label on 'Service Area by Fiscal Year' plot. 

Data/lookupcode.csv, budget_proj/budget_app/migrations/0005_auto_20170418_0251.py, budget_proj/budget_app/migrations/0006_index_and_alphabetize.py, budget_proj/budget_app/models.py, sql/lookupcode.sql, sql/lookupcode_sqlite.sql
'EO'='Elected Officials' is a derived Service Area (see Pull Request #146), so it does not appear in the original extract of budget history data that we received (https://github.com/hackoregon/team-budget/blob/master/Data/HackOregon_hx_budget_data_ASV2_extracted.csv). At some point, when we have a pipeline for data from the City to Hack Oregon, we should worry about how this value gets defined. For now, I just inserted it manually into the CSV file, so that it can be loaded into the budget database. This value enables a client to translate the 'EO' value from a service_area_code or sa_calced field in a /budget/history/service_area response into a displayable string for presentation on a UI.
=> Added 'EO' code to service_area_code types.
